#' Plot selectivities by age, year, fleet, and model
#'
#' @param sels selectivity data frame generated by \code{get_selectivities}
#' @param fleet fleets to plot: "fsh" (fishery), "ind" (survey), or "all" (both)
#'
#' @return a ggplot2 plot object
#' @export
#'
#' @examples
#' 
#' \dontrun{
#' 
#' oldnewMods <- combineModels(mod0.00,mod_prev)
#'selectivities <- get_selectivities(oldnewMods)
#'plot_selectivities(selectivities)
#' 
#' }
#' 
plot_selectivities <- function(sels, fleet = "fsh") {
  if (fleet == "all") {
    fleet <- unique(sels$fleet_type)
  }
  
  sels <- sels %>%
    dplyr::filter(fleet_type %in% fleet)
  
  if (nrow(sels) == 0){
    stop("Specified fleet for plotting not in list of available fleets. Must be one of 'fsh','ind', or 'all'")
  }
    sels %>% 
    ggplot() +
    ggridges::geom_density_ridges(
      aes(
        x = age,
        y = year,
        height = selectivity,
        group = interaction(model, year),
        fill = model
      ),
      stat = "identity",
      color = "transparent",
      alpha = 0.4,
      scale = 4
    ) +
    ggplot2::facet_grid(fleet_type ~ fleet_number, labeller = ggplot2::label_both) + 
    theme_jjm() + 
    ggplot2::scale_x_continuous(name = "Age") + 
    ggplot2::scale_y_continuous(name = "Year")
  
}